version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application
artifacts:
  files:
    - '**/*'     # Include all files in artifact (or specify only needed files)
